# Generated by Django 3.2.25 on 2025-12-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0002_auto_20210329_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='file',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='message', to='django_private_chat2.UploadedFile', verbose_name='File'),
        ),
    ]
